#%RAML 1.0 DataType
type: object
displayName: "Change password of Users"
properties:
   oldPassword:
     type: object
     required : true
     displayName: "oldPassword"
     properties:
      value:
       type: string
       displayName : "value"
       example: "Abc@12345"
   newPassword:
      type: object
      required: true
      displayName: "newPassword"
      properties:
       value:
        type: string
        displayName : "value"
        example: "New@uj67543"