#%RAML 1.0 Library
usage:
types:
    createuser: !include createuser-dataType.raml
    forgetpassword: !include forgetpassword-dataType.raml 
    primaryauthentication: !include primaryauthentication-dataType.raml
    createsession: !include createsession-dataType.raml
    changepassword: !include changepassword-dataType.raml